---
- include: install-packages.yml
- include: ensure-dirs.yml

- name: Start the jenkins service
  service: name={{ jenkins_service_name }} state=started enabled=yes
  tags: [service,jenkins]

- name: Wait on Jenkins UI
  command  : curl --head --silent {{ jenkins_url }}/cli
  register : jenkins_check_available
  until    : (jenkins_check_available.stdout.find("200 OK") != -1) or
             (jenkins_check_available.stdout.find("403 Forbidden") != -1)
  retries  : 12
  delay    : 5
  changed_when : False

- name: Get jenkins-cli
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10

- include: install-plugins.yml
